title: [ML Team 7 - Summer 2024]
description: [Exploring sentiment analysis & detection with machine learning!]
remote_theme: pages-themes/slate@v0.2.0
markdown: GFM
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
